blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import RecordListView, RecordDetailView, RecordCreateView, RecordUpdateView, RecordDeleteView, \
    toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('records/', RecordListView.as_view(), name='record_list'),
    path('records/<slug:slug>/', RecordDetailView.as_view(), name='record_detail'),
    path('records_create/', RecordCreateView.as_view(), name='create_record'),
    path('records_update/<slug:slug>/', RecordUpdateView.as_view(), name='update_record'),
    path('records_delete/<slug:slug>/', RecordDeleteView.as_view(), name='delete_record'),
    path('toggle/<slug:slug>/', toggle_activity, name='toggle_activity')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include

from mailing.apps import MailingConfig
from mailing.views import HomePageView, ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, \
    MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, MailingDeleteView, set_mailing_active, \
    MessageListView, MessageCreateView, MessageUpdateView, MessageDeleteView, MailingLogListView

app_name = MailingConfig.name

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),

    path('client_list/', ClientListView.as_view(), name='client_list'),
    path('client_create/', ClientCreateView.as_view(), name='client_create'),
    path('client_update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client_delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),

    path('mailing_list', MailingListView.as_view(), name='mailing_list'),
    path('mailing_detail/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing_create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing_update/<int:pk>/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing_delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),

    path('message_list/', MessageListView.as_view(), name='message_list'),
    path('message_create/', MessageCreateView.as_view(), name='message_create'),
    path('message_update/<int:pk>/', MessageUpdateView.as_view(), name='message_update'),
    path('message_delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),

    path('mailing_log_list/', MailingLogListView.as_view(), name='mailing_log_list'),

    path('set_mailing_active/<int:pk>', login_required(set_mailing_active), name='set_mailing_active')

]

mailing/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

# Create your models here.

NULLABLE = {'null': True, 'blank': True}


class Client(models.Model):
    email = models.EmailField(max_length=100, unique=True, verbose_name='email')
    full_name = models.CharField(max_length=100, verbose_name='full name')
    comment = models.TextField(verbose_name='comment', **NULLABLE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='User', **NULLABLE)

    def __str__(self):
        return f'{self.email} - {self.full_name}'

    class Meta:
        verbose_name = 'Client'
        verbose_name_plural = 'Clients'


class Message(models.Model):
    subject = models.CharField(max_length=150, verbose_name='Email subject')
    body = models.TextField(verbose_name="Message's text")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='User', **NULLABLE)

    def __str__(self):
        return f'{self.subject}'

    class Meta:
        verbose_name = 'Message'
        verbose_name_plural = 'Messages'


class Mailing(models.Model):
    DAILY = 'daily'
    WEEKLY = 'weekly'
    MONTHLY = 'monthly'

    FREQUENCY_CHOICES = [
        ('DAILY', 'daily'),
        ('WEEKLY', 'weekly'),
        ('MONTHLY', 'monthly'),
    ]

    CREATED = 'CREATED'
    STARTED = 'STARTED'
    FINISHED = 'FINISHED'

    STATUS_CHOICES = [
        (CREATED, 'created'),
        (STARTED, 'started'),
        (FINISHED, 'finished')
    ]

    mailing_date = models.DateTimeField(verbose_name='mailing date', default=timezone.now)
    mailing_time = models.TimeField(verbose_name='mailing time')
    frequency = models.CharField(max_length=50, verbose_name='frequency', choices=FREQUENCY_CHOICES)
    mailing_status = models.CharField(max_length=50, verbose_name='mailing status', choices=STATUS_CHOICES, default=CREATED)

    clients = models.ManyToManyField(Client, verbose_name='Clients for mailing')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='Message')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='User', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='is active?')

    def __str__(self):
        return f'ID: {self.id}, user: {self.user}'

    class Meta:
        verbose_name = 'mailing'
        verbose_name_plural = 'mailing'
        permissions = [
            (
                'set_mailing_active',
                'Can set mailing active'
            ),
        ]


class MailingLog(models.Model):
    SENT = 'sent'
    FAILED = 'failed'
    PENDING = 'pending'

    STATUS_CHOICES = [
        ('SENT', 'sent'),
        ('FAILED', 'failed'),
        ('PENDING', 'pending')
    ]

    attempt_time = models.DateTimeField(auto_now_add=True, verbose_name='time of attempt')
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, verbose_name='status of attempt')
    server_response = models.TextField(max_length=200, verbose_name='server response')
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='mailing')

    def __str__(self):
        return f'Log for {self.mailing.id}'

    class Meta:
        verbose_name = 'Mailing log'
        verbose_name_plural = 'Mailing logs'

mailing/forms.py
from django import forms
from mailing.models import Mailing


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        fields = '__all__'
        exclude = ('user',)

mailing/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView, DetailView

from blog.models import Blog
from mailing.forms import MailingForm
from mailing.models import Client, Mailing, Message, MailingLog

from mailing.services import cache_message


# Create your views here.


class HomePageView(TemplateView):
    template_name = 'mailing/index.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        context_data['count_mailing_all'] = Mailing.objects.all().count()
        context_data['count_mailing_active'] = Mailing.objects.filter(is_active=True).count()
        context_data['count_unique_clients'] = Client.objects.distinct().count()

        context_data['blog'] = Blog.objects.all().order_by('?')[:3]

        return context_data


class ClientListView(LoginRequiredMixin, ListView):
    model = Client

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.has_perm('mailing.set_mailing_active'):
            return queryset

        return queryset.filter(user=self.request.user)


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    fields = ('email', 'full_name', 'comment')
    success_url = reverse_lazy('mailing:client_list')

    def form_valid(self, form):
        client = form.save()
        client.user = self.request.user
        client.save()
        return super().form_valid(form)


class ClientUpdateView(UserPassesTestMixin, UpdateView):
    model = Client
    fields = ('email', 'full_name', 'comment')
    success_url = reverse_lazy('mailing:client_list')

    def test_func(self):
        client = self.get_object()
        user = self.request.user
        return user.is_authenticated and (client.user == user or user.has_perm('mailing.change_client'))


class ClientDeleteView(UserPassesTestMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailing:client_list')

    def test_func(self):
        client = self.get_object()
        user = self.request.user
        return user.is_authenticated and (client.user == user or user.has_perm('mailing.delete_client'))


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.has_perm('mailing.view_mailing'):
            return queryset

        return queryset.filter(user=self.request.user)


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.has_perm('mailing.view_mailing') or self.request.user == self.object.user:
            return self.object
        raise HttpResponseForbidden


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.user = self.request.user
            self.object.save()
        return super().form_valid(form)


class MailingUpdateView(UserPassesTestMixin, UpdateView):
    model = Mailing
    fields = '__all__'
    success_url = reverse_lazy('mailing:mailing_list')

    def test_func(self):
        mailing = self.get_object()
        user = self.request.user
        return user.is_authenticated and (mailing.user == user or user.has_perm('mailing.change_mailing'))


class MailingDeleteView(UserPassesTestMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing:mailing_list')

    def test_func(self):
        mailing = self.get_object()
        user = self.request.user
        return user.is_authenticated and (mailing.user == user or user.has_perm('mailing.delete_mailing'))


class MessageListView(LoginRequiredMixin, ListView):
    model = Message

    def get_queryset(self):
        queryset = cache_message(Message, 'message')
        if self.request.user.has_perm('mailing.set_mailing_active'):
            return queryset
        return queryset.filter(user=self.request.user)


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    fields = ('subject', 'body',)
    success_url = reverse_lazy('mailing:message_list')

    def form_valid(self, form):
        message = form.save()
        message.user = self.request.user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(UserPassesTestMixin, UpdateView):
    model = Message
    fields = ('subject', 'body',)
    success_url = reverse_lazy('mailing:message_list')

    def test_func(self):
        message = self.get_object()
        user = self.request.user
        return user.is_authenticated and (message.user == user or user.has_perm('mailing.change_message'))


class MessageDeleteView(UserPassesTestMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('mailing:message_list')

    def test_func(self):
        message = self.get_object()
        user = self.request.user
        return user.is_authenticated and (message.user == user or user.has_perm('mailing.delete_message'))


class MailingLogListView(LoginRequiredMixin, ListView):
    model = MailingLog
    template_name = 'mailing/mailing_log_list.html'

    def get_queryset(self):
        queryset = cache_message(MailingLog, 'mailing_log')
        if self.request.user.has_perm('mailing.set_mailing_active'):
            return queryset
        return queryset.filter(user=self.request.user)


@permission_required(perm='mailing.set_mailing_active')
def set_mailing_active(request, pk):
    obj = get_object_or_404(Mailing, pk=pk)
    if obj.is_active:
        obj.is_active = False
    else:
        obj.is_active = True
    obj.save()
    return redirect(request.META.get('HTTP_REFERER'))

mailing/templates/mailing/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Рассылка</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>
</head>


<body>

<header class="blog-header py-3 d-flex justify-content-center align-items-center h-100">
    <div class="container">
        <div class="row">
            {% include 'mailing/includes/inc_main_menu.html' %}
        </div>
    </div>
</header>
<div class="container">
    <div class="row p-5 justify-content-lg-center">
        {% block content %}
        {% endblock %}
    </div>
</div>

</body>
</html>

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="container">
        <h1 class="text-center">Клиенты</h1>
        <div class='table-responsive'>
            <table class="table table-striped table-bordered">
                <thead class="thead-dark">
                <tr>
                    <th scope="col" style="text-align: center">ID</th>
                    <th scope="col" style="text-align: center">ФИО</th>
                    <th scope="col" style="text-align: center">Email</th>
                    <th scope="col" style="text-align: center">Комментарий</th>
                    {% if perms.mailing.set_mailing_status %}
                        <th scope="col" style="text-align: center">Пользователь</th>
                    {% endif %}
                    <th scope="col" style="text-align: center"></th>
                </tr>
                </thead>
                <tbody>
                {% for obj in object_list %}
                    <tr>
                        <td class="text-center">{{ obj.pk }}</td>
                        <td class="text-center">{{ obj.full_name }}</td>
                        <td class="text-center">{{ obj.email }}</td>
                        <td class="text-center">{{ obj.comment }}</td>
                        {% if perms.mailing.set_mailing_status %}
                            <td class="text-center">{{ obj.user }}</td>
                        {% endif %}

                        <td class="text-center">
                            {% if obj.user == user or user.is_superuser %}
                                <a href="{% url 'mailing:client_update' obj.pk %}"
                                   class="btn btn-warning">Изменить</a>
                                <a href="{% url 'mailing:client_delete' obj.pk %}"
                                   class="btn btn-danger">Удалить</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="container text-center">
            <a href="{% url 'mailing:client_create' %}" class="btn btn-outline-dark btn-lg my-3"
               style="border-radius: 25px; padding: 10px 25px; font-size: 20px; font-weight: bold;">Добавить клиента</a>
        </div>
    </div>
    <style>
        .btn {
            margin-top: 5px;
            padding: 10px 20px;
            border-radius: 20px;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }

        .btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
        }

        .btn:active {
            transform: translateY(-1px);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }
    </style>
{% endblock %}

mailing/templates/mailing/index.html
{% extends 'mailing/base.html' %}
{% load tags %}
{% block content %}
    <div class="container-h text-center my-5 py-5">
        <div class="row">
            <div class="col-md-10 mx-auto">
                <div class="card mb-4 box-shadow">
                    <div class="card-header bg-dark text-white">
                        <h1 class="font-weight-normal">Cервис рассылок</h1>
                    </div>
                    <div class="card-body text-muted">
                        <ul class="list-unstyled mt-3 mb-4">
                            <li>Всего рассылок : {{ count_mailing_all }}</li>
                            <li>Активных рассылок всего : {{ count_mailing_active }}</li>
                            <li>Количество уникальных клиентов для рассылок : {{ count_unique_clients }}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <h1>Статьи</h1>

        <div class="container">
            <div class="row">
                {% for item in blog %}
                    <div class="col-md-4 mb-4">
                        <div class="card h-100">
                            <h3 class="card-header bg-dark"><a
                                    href="{% url 'blog:record_detail' item.slug %}"
                                    style="color: white; margin: 0;">{{ item.title }}</a></h3>
                            <div class="card-body">
                                <h5 class="card-title">{{ item.body | truncatechars:100 }}</h5>
                                <img src="{% mediapath item.picture %}"
                                     class="card-img-top mx-auto d-block img-fluid" alt=""
                                     style="width: auto; height: auto;">
                                <ul>
                                    <li><a class="card-text">Просмотры: {{ item.views }}</a></li>
                                    <li><p class="card-text">Дата публикации: {{ item.created_date }}</p></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <style>
        .btn {
            margin-top: 5px;
            padding: 10px 20px;
            border-radius: 20px;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }

        .btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
        }

        .btn:active {
            transform: translateY(-1px);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }

        .container-h {
            background-color: #f7f7f7;
            border: 1px solid #ddd;
            box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.1);
            padding: 20px;
        }

        .card-header h1 {
            font-size: 2.5rem;
            font-weight: bold;
            letter-spacing: 0.1em;
            margin-bottom: 1rem;
        }

        .card-body {
            font-size: 1.2rem;
            line-height: 1.6;
        }

        ul li {
            margin-bottom: 0.5rem;
        }

        .card:hover {
            transform: translateY(-5px);
            box-shadow: 4px 4px 10px rgba(0, 0, 0, 0.2);
            transition: all 0.3s ease;
        }
    </style>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html' %}

{% block content %}

    <div class="container">
        <div class="card text-center">
            <div class="card-header">
                {{ object.message }}
            </div>
            <div class="card-body">
                <h5 class="card-title">{{ object.mailing_time }}</h5>
                <p class="card-text">Периодичность рассылки: {{ object.get_frequency_display }}</p>
                <p class="card-text">Получатели:
                    {% for obj in object.client.all %}
                        {{ obj.full_name }}
                    {% endfor %}

                </p>
                {% if object.user == user or user.is_superuser %}
                    <a href="{% url 'mailing:mailing_update' object.pk %}" class="btn btn-warning">Изменить</a>
                    <a href="{% url 'mailing:mailing_delete' object.pk %}" class="btn btn-danger">Удалить</a>
                {% endif %}
                {% if perms.mailing.set_mailing_status or user.is_superuser %}
                    {% if object.is_active %}
                        <a class="btn btn-info" href="{% url 'mailing:set_mailing_active' object.pk %}">Деактивировать
                            рассылку</a>
                    {% else %}
                        <a class="btn btn-info" href="{% url 'mailing:set_mailing_active' object.pk %}">Активировать
                            рассылку</a>
                    {% endif %}
                {% endif %}
            
                <br><br>
                <a href="{% url 'mailing:mailing_list' %}" class="btn btn-secondary">Все рассылки</a>
            </div>
            <div class="card-footer text-muted">
                Статус рассылки: {{ object.is_active }}

            </div>
        </div>
    </div>
    <style>
        .card {
            margin-top: 20px;
            border: 1px solid #ddd;
            border-radius: 5px;
            box-shadow: 2px 4px rgba(0, 0, 0, 0.3);
        }

        .card-header {
            font-size: 24px;
            background-color: #eee;
            font-weight: bold;
        }

        .card-body {
            text-align: center;
        }

        .card-text {
            font-size: 18px;
        }

        .btn {
            padding: 10px 20px;
            border-radius: 20px;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }

        .btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
        }

        .btn:active {
            transform: translateY(-1px);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }
    </style>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="container">
        <h1 class="text-center">Рассылки</h1>
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
            <tr>
                <th scope="col" style="text-align: center">ID</th>
                <th scope="col" style="text-align: center">Дата рассылки</th>
                <th scope="col" style="text-align: center">Время рассылки</th>
                <th scope="col" style="text-align: center">Периодичность</th>
                <th scope="col" style="text-align: center">Статус рассылки</th>
                <th scope="col" style="text-align: center">Статус активности</th>
                <th scope="col" style="text-align: center">Сообщение</th>
                <th scope="col" style="text-align: center"></th>
            </tr>
            </thead>
            <tbody class="table-group-divider table-divider-primary">

            {% for obj in object_list %}
                 {% if obj.user == user or perms.mailing.view_mailing %}
                <tr>
                    <th class="text-center">{{ obj.pk }}</th>
                    <td class="text-center">{{ obj.mailing_date }}</td>
                    <td class="text-center">{{ obj.mailing_time }}</td>
                    <td class="text-center">{{ obj.get_frequency_display }}</td>
                    <td class="text-center">{{ obj.get_mailing_status_display }}</td>
                    <td class="text-center">{{ obj.is_active }}</td>
                    <td class="text-center">{{ obj.message }}</td>
                    <td class="text-center"><a href="{% url 'mailing:mailing_detail' obj.pk %}"
                                               class="btn btn-dark">Перейти к рассылке</a>
                    </td>

                </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
        <div class="container" style="text-align: center">

            <a href="{% url 'mailing:mailing_create' %}" class="btn btn-outline-dark btn-lg my-3"
               style="border-radius: 25px; padding: 10px 25px; font-size: 20px; font-weight: bold;">Создать рассылку</a>
        </div>
    </div>
    <style>
        .btn {
            padding: 10px 20px;
            border-radius: 20px;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }

        .btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
        }

        .btn:active {
            transform: translateY(-1px);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }
    </style>
{% endblock %}

mailing/templates/mailing/mailing_log_list.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="container">
        <h1 class="text-center">Статус рассылки</h1>
        <div class='table-responsive'>
            <table class="table table-striped table-bordered">
                <thead class="thead-dark">
                <tr>
                    <th scope="col" style="text-align: center">ID</th>
                    <th scope="col" style="text-align: center">Дата и время последней попытки</th>
                    <th scope="col" style="text-align: center">Статус попытки</th>
                    <th scope="col" style="text-align: center">Ответ почтового сервера</th>
                    <th scope="col" style="text-align: center">Рассылки</th>
                    <th scope="col" style="text-align: center">Статус рассылки</th>

                    <th scope="col" style="text-align: center">Получатели</th>
                    <th scope="col" style="text-align: center"></th>
                </tr>
                </thead>
                <tbody>
                {% for obj in object_list %}
                    <tr>
                        <td class="text-center">{{ obj.pk }}</td>
                        <td class="text-center">{{ obj.attempt_time }}</td>
                        <td class="text-center">{{ obj.get_status_display }}</td>
                        <td class="text-center">{{ obj.server_response }}</td>
                        <td class="text-center">{{ obj.mailing }}</td>
                        <td class="text-center">{{ obj.mailing.get_mailing_status_display }}</td>
                        <td  {% for rec in obj.mailing.client.all %}
                            class="text-center">  {{ rec.full_name }}</td>
                        {% endfor %}

                        <td class="text-center">
                            <a href="{% url 'mailing:mailing_detail' obj.mailing.pk %}" class="btn btn-dark">Перейти
                                к
                                рассылке</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="container text-center">
            <a href="{% url 'mailing:mailing_create' %}" class="btn btn-outline-dark btn-lg my-3"
               style="border-radius: 25px; padding: 10px 25px; font-size: 20px; font-weight: bold;">Создать рассылку</a>
        </div>
    </div>
    <style>
        .btn {
            margin-top: 5px;
            padding: 10px 20px;
            border-radius: 20px;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }

        .btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
        }

        .btn:active {
            transform: translateY(-1px);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }
    </style>
{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="container">
        <h1 class="text-center">Сообщения</h1>
        <div class='table-responsive'>
            <table class="table table-striped table-bordered">
                <thead class="thead-dark">
                <tr>
                    <th scope="col" style="text-align: center">ID</th>
                    <th scope="col" style="text-align: center">Тема письма</th>
                    <th scope="col" style="text-align: center">Тело сообщения</th>
                    {% if perms.mailing.set_mailing_active %}
                        <th scope="col" style="text-align: center">Пользователь</th>
                    {% endif %}
                    <th scope="col" style="text-align: center"></th>
                </tr>
                </thead>
                <tbody>
                {% for obj in object_list %}
                    <tr>
                        <td class="text-center">{{ obj.pk }}</td>
                        <td class="text-center">{{ obj.subject }}</td>
                        <td class="text-center">{{ obj.body }}</td>
                        {% if perms.mailing.set_mailing_active %}
                            <td class="text-center">{{ obj.user }}</td>
                        {% endif %}

                        <td class="text-center">
                            {% if obj.user == user or user.is_superuser %}
                                <a href="{% url 'mailing:message_update' obj.pk %}" class="btn btn-warning">Изменить</a>
                                <a href="{% url 'mailing:message_delete' obj.pk %}" class="btn btn-danger">Удалить</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="container text-center">
            <a href="{% url 'mailing:message_create' %}" class="btn btn-outline-dark btn-lg my-3"
               style="border-radius: 25px; padding: 10px 25px; font-size: 20px; font-weight: bold;">Добавить
                сообщение</a>
        </div>
    </div>
    <style>
        .btn {
            margin-top: 5px;
            padding: 10px 20px;
            border-radius: 20px;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }

        .btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
        }

        .btn:active {
            transform: translateY(-1px);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }
    </style>
{% endblock %}